---
# Handlers pour le role network

- name: apply netplan
  command: netplan apply
  async: 45
  poll: 0
  ignore_errors: yes
  # Note: On ignore les erreurs car la connexion peut être coupée lors de l'application
